# https://taskfile.dev

version: '3'

tasks:

  test:
    cmds:
      - go test -v ./...

  lint:
    cmds:
      - golangci-lint run

  bench:
    cmds:
      - go test ./... -run=Benchmark -bench=.

  cover:
    cmds:
      - go test ./... --cover